import { GenericSkill } from "../../types/common"

const nbSkills: Array<GenericSkill> = [
    {
        name: "Soul Tether",
        icon: "/icons/skills/nb/soulShred.png",
        id: 35460,
        castTime: 0.5,
        target: "Area",
        radius: 8,
        duration: 8,
        cost:{
            resourceName: "Ultimate",
            amount:150,
        },
        description: '<p class="skillDescription">Ravage nearby enemies\' souls with a night rune, dealing 6560 Magic Damage, healing for half the damage, and stunning them for 4 seconds. </p><p class="skillDescription">Ravaged enemies are tethered to you for 8 seconds, and while they remain within 10 meters, you siphon 1142 Health from them every second.</p><p class="skillDescription">An ally can target a ravaged enemy and activate the Soul Leech synergy, dealing 5689 Magic Damage to them and healing for the damage caused.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Heals for half the initial damage caused. Tether to enemies hit, dealing constant damage and healing for damage caused.</p>',
    },
    {
        name: "Healthy Offering",
        icon: "/icons/skills/nb/healthyOffering.png",
        id: 34727,
        castTime: 0,
        target: "Cone",
        radius: 28,
        cost:{
            resourceName: "Magicka",
            amount:3510,
        },
        description: '<p class="skillDescription">Pour out your lifesblood and channel the arcane, healing yourself or an ally in front of you for 6560 Health, while draining 1080 Health from yourself over 3 seconds.</p><p class="skillDescription">After casting, gain Minor Mending for 10 seconds, increasing your healing done by 8%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Grants you Minor Mending after casting, increasing your healing done.</p>',
    },
    {
        name: "Siphoning Attacks",
        icon: "/icons/skills/nb/siphoning.png",
        id: 36935,
        castTime: 0,
        target: "Self",
        cost:{
            resourceName: "Health",
            amount:4000,
        },
        description: '<p class="skillDescription">Channel a portion of your soul to convert Health to 2600 Magicka and Stamina.</p><p class="skillDescription">While slotted on either bar, your soul yearns for the warmth of life. All damage you deal heals you for 1250 Health and restores 200 Magicka and Stamina, up to once every 1 second.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Increases the Magicka and Stamina restored, and the heal now also restores Magicka and Stamina.</p>',
    },
    {
        name: "Power Extraction",
        icon: "/icons/skills/nb/powerExtraction.png",
        id: 36901,
        castTime: 0,
        target: "Area",
        radius: 8,
        duration: 30,
        cost:{
            resourceName: "Stamina",
            amount:2983,
        },
        description: '<p class="skillDescription">Siphon the vigor from your enemies\' blood, dealing 3175 Disease Damage to all nearby enemies.</p><p class="skillDescription">If an enemy is hit you gain Major Brutality and Sorcery, and Minor Courage increasing your Weapon and Spell Damage by 20% and 215 for 30 seconds. Enemies hit have Minor Cowardice applied to them for 10 seconds, reducing their Weapon and Spell Damage by 215.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Converts to a Stamina ability that deals Disease Damage. Applies Minor Cowardice to enemies hit and grants Minor Courage to you.</p>',
    },
    {
        name: "Phantasmal Escape",
        icon: "/icons/skills/nb/phantasmal.png",
        id: 35419,
        castTime: 0,
        target: "Self",
        duration: 20,
        cost:{
            resourceName: "Magicka",
            amount:3780,
        },
        description: '<p class="skillDescription">Surround yourself in a phantasmic aura to gain Major Evasion, reducing damage from area attacks by 20% for 20 seconds.</p><p class="skillDescription">Activating this ability removes all snares and immobilizations from you and grants immunity to them for 4 seconds.</p><p class="skillDescription">While active, taking direct damage reduces the cost of your next Roll Dodge by 10%, up to a maximum of 100%. This effect can stack up to once every half second.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Grants snare and immobilization immunity for a short duration.</p>',
    },
    {
        name: "Shadowy Disguise",
        icon: "/icons/skills/nb/shadowy.png",
        id: 25380,
        castTime: 0,
        target: "Self",
        duration: 3,
        cost:{
            resourceName: "Magicka",
            amount:4050,
        },
        description: '<p class="skillDescription">Cloak yourself in shadow to become invisible. When moving your Magicka Recovery is disabled and when not moving Shadowy Disguise is half cost. Your next direct damage attack will Critically Strike.</p><p class="skillDescription">When Shadowy Disguise begins or ends, you gain Born From Shadow for 10 seconds, increasing your damage done to monsters by 10%.</p><p class="skillDescription">While slotted on either bar, gain Major Prophecy and Major Savagery, increasing your Spell and Weapon Critical rating by 2629.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Guarantees a Critical Strike on your next attack after activating. Cost decreases as the ability ranks up.</p>',
    },
    {
        name: "Refreshing Path",
        icon: "/icons/skills/nb/path.png",
        id: 35460,
        castTime: 0,
        target: "Area",
        targetAreaX:17,
        targetAreaY:7,
        radius: 17,
        duration: 10,
        cost:{
            resourceName: "Magicka",
            amount:3510,
        },
        description: '<p class="skillDescription">Create a corridor of shadows for 10 seconds, granting you and allies in the area Major Expedition, Minor Endurance, and Minor Intellect, increasing Movement Speed by 30%, as well as Stamina and Magicka Recovery by 15%. Effect persists for 4 seconds after leaving the path.</p><p class="skillDescription">Heals 794 Health to you and allies in the area every 1 second.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Path also heals you and your allies and increases their Magicka and Stamina Recovery.</p>',
    },
    {
        name: "Incapacitating Strike",
        icon: "/icons/skills/nb/incap.png",
        id: 35460,
        castTime: 0.4,
        target: "Enemy",
        range: 7,
        cost:{
            resourceName: "Ultimate",
            amount:70,
        },
        description: '<p class="skillDescription">Ravage an enemy with a swift strike, dealing 6998 Disease Damage and causing them to take 20% more damage from your attacks for 8 seconds.</p><p class="skillDescription">If cast with 120 or more Ultimate, you instead deal 7698 Disease Damage, stun the enemy for 3 seconds, and increase the duration of the damage taken effect to 12 seconds.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Deals Disease Damage. Improves the ability significantly if cast with more Ultimate.</p>',
    },
    {
        name: "Concealed Weapon",
        icon: "/icons/skills/nb/concealed.png",
        id: 25267,
        castTime: 0,
        target: "Enemy",
        range: 7,
        cost:{
            resourceName: "Magicka",
            amount:2295,
        },
        description: '<p class="skillDescription">Slash an enemy, dealing 4658 Magic Damage. </p><p class="skillDescription">If you strike an enemy from their flank you set them Off Balance.</p><p class="skillDescription">When you leave Sneak or invisibility while in combat, increase your damage done with this ability by 10% for 15 seconds.</p><p class="skillDescription">While slotted on either bar, you gain Minor Expedition, increasing your Movement Speed by 15%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Deals increased damage, which furthers when leaving Sneak or invisibility. While slotted you gain Minor Expedition.</p>',
    },
    {
        name: "Merciless Resolve",
        icon: "/icons/skills/nb/merciless.png",
        id: 61919,
        castTime: 0,
        target: "Enemy",
        range: 28,
        duration: 8,
        cost:{
            resourceName: "Magicka",
            amount:1890,
        },
        description: '<p class="skillDescription">When slotted on either bar, you focus with lethal intent, causing your Light and Heavy Attacks to generate a stack of Merciless Resolve, increasing your Weapon and Spell Damage by 60 up to 5 times. Fully-charged Heavy Attacks grant two stacks.</p><p class="skillDescription">When at full stacks, you can consume them all to fire a spectral arrow to deal 8661 Magic Damage, and heal for 50% of the damage dealt if you are within melee range.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Increases the damage and healing of the spectral arrow.</p>',
    },
]
export default nbSkills

/*
{
        name: "",
        icon: "/icons/skills/nb/.png",
        id: 35460,
        castTime: 0,
        target: "Area",
        radius: 8,
        duration: 8,
        cost:{
            resourceName: "",
            amount:,
        },
        description: '<p class="skillDescription"></p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span></p>',
    },
*/