import { GenericSkill } from "../../types/common"

const sorcSkills: Array<GenericSkill> = [
    {
        name: "Haunting Curse",
        id: 24330,
        castTime: 0,
        target: "Enemy",
        range: 28,
        duration: 12,
        cost: {
            resourceName: "Magicka",
            amount: 2970,
        },
        description: '<p class="skillDescription">Curse an enemy with a destructive rune, dealing 5467 Magic Damage to the target and 2514 Magic Damage to all other nearby enemies after 3.5 seconds.</p><p class="skillDescription">The curse will continue to haunt the enemy and explode a second time, dealing 5467 Magic Damage to the target and 2514 Magic Damage to all other nearby enemies after an additional 8.5 seconds.</p><p class="skillDescription">You can have only one Haunting Curse active at a time.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>The curse will continue to haunt the enemy and explode a second time.</p>',
        icon: "/icons/skills/sorc/haunting.png",
    },
    {
        name: "Hardened Ward",
        id: 29489,
        castTime: 0,
        target: "Self",
        duration: 6,
        cost: {
            resourceName: "Magicka",
            amount: 4320,
        },
        description: '<p class="skillDescription">Conjure globes of Daedric energy for protection, granting a damage shield for you and your pets that absorbs 9155 damage for 6 seconds. If no pets are affected, you also heal for 3000 Health.</p><p class="skillDescription">This ability scales off the higher of your Max Health or Magicka and the shield is capped at 72% of your Max Health.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Damage shield absorbs more and has a higher capped value.</p>',
        icon: "/icons/skills/sorc/hardened.png",
    },
    {
        name: "Bound Aegis",
        id: 24163,
        castTime: 0,
        target: "Self",
        duration: 5,
        cost: {
            resourceName: "Magicka",
            amount: 4050,
        },
        description: '<p class="skillDescription">Protect yourself with the power of Oblivion, creating a suit of Daedric mail that increases your block mitigation by 40% for 5 seconds.</p><p class="skillDescription">While slotted on either ability bar, your Max Magicka is increased by 8% and you gain Minor Resolve and Minor Protection, increasing your Physical and Spell Resistance by 2974 and reducing your damage taken by 5%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Passively grants Minor Resolve while slotted. Increases the potency and duration of the block mitigation.</p>',
        icon: "/icons/skills/sorc/boundAegis.png",
    },
    {
        name: "Crystal Weapon",
        id: 46331,
        castTime: 0,
        target: "Self",
        duration: 6,
        cost: {
            resourceName: "Stamina",
            amount: 2295,
        },
        description: '<p class="skillDescription">Encase your weapon in dark crystals for 6 seconds, causing your next two Light or Heavy Attacks to deal additional damage and reduce the target\'s Armor by 1000 for 5 seconds. The first hit deals 3811 Physical Damage and the second deals 1523 Physical Damage.</p><p class="skillDescription">After casting, your next non-Ultimate ability used within 3 seconds costs 10% less.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Converts the ability into an instant cast Stamina ability, which causes your next two Light or Heavy Attacks to deal bonus Physical Damage and reduce the enemy\'s Armor.</p>',
        icon: "/icons/skills/sorc/crystalWeapon.png",
    },
    {
        name: "Dark Conversion",
        id: 24589,
        castTime: 1,
        target: "Self",
        duration: 20,
        cost: {
            resourceName: "Stamina",
            amount: 3240,
        },
        description: '<p class="skillDescription">Bargain with darkness to restore 10000 Health and 4500 Magicka instantly, and an additional 3000 Magicka over 20 seconds.</p><p class="skillDescription">The exchange also grants you Minor Berserk for 20 seconds, increasing your damage done by 5%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Increases the amount of Health and Magicka restored.</p>',
        icon: "/icons/skills/sorc/darkConv.png",
    },
    {
        name: "Absorption Field",
        id: 28348,
        castTime: 0,
        target: "Ground",
        radius: 8,
        range: 28,
        duration: 12,
        cost: {
            resourceName: "Ultimate",
            amount: 225,
        },
        description: '<p class="skillDescription">Create a globe of magic suppression for 12 seconds, removing and preventing all enemy area of effect abilities from occurring in the area.</p><p class="skillDescription">Enemies within the globe are stunned, while enemy players will be silenced rather than stunned.</p><p class="skillDescription">The globe also heals you and your allies for 1891 Health every 1 second.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>The globe also heals you and your allies standing inside it.</p>',
        icon: "/icons/skills/sorc/negejtus.png",
    },
    {
        name: "Energy Overload",
        id: 28348,
        castTime: 0,
        target: "Self",
        cost: {
            resourceName: "Ultimate",
            amount: 25,
        },
        description: '<p class="skillDescription">Charge your fists with the power of the storm, replacing your Light and Heavy Attacks with new, stronger abilities.</p><p class="skillDescription">Light Attacks become lightning bolts, dealing 4373 Shock Damage to an enemy up to 28 meters away.</p><p class="skillDescription">Heavy Attacks blast enemies in a 4 x 6 area for 3936 Shock Damage.</p><p class="skillDescription">The attacks restore 1200 Magicka and Stamina, and deplete Ultimate until you run out, or the ability is toggled off.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>While active your Light and Heavy Attacks restore Magicka and Stamina.</p>',
        icon: "/icons/skills/sorc/overload.png",
    },
    {
        name: "Hurricane",
        id: 23231,
        castTime: 0,
        target: "Area",
        radius: 5,
        duration: 20,
        cost: {
            resourceName: "Stamina",
            amount: 2295,
        },
        description: '<p class="skillDescription">Manifest yourself as pure air, buffeting nearby enemies with wind dealing 873 Physical Damage every 2 seconds for 20 seconds. The winds grow in damage and size, increasing up to 120% more damage and up to 9 meters in size.</p><p class="skillDescription">While in this form you gain Major Resolve and Minor Expedition, increasing your Physical and Spell Resistance by 5948 and your Movement Speed by 15%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Converts into a Stamina ability and deals Physical Damage. Increases in size and damage the longer it is active. Grants Minor Expedition while active, increasing your Movement Speed.</p>',
        icon: "/icons/skills/sorc/hurricane.png",
    },
    {
        name: "Critical Surge",
        id: 23231,
        castTime: 0,
        target: "Self",
        duration: 33,
        cost: {
            resourceName: "Magicka",
            amount: 4050,
        },
        description: '<p class="skillDescription">Invoke Meridia\'s name to gain Major Brutality and Sorcery, increasing your Weapon and Spell Damage by 20% for 33 seconds.</p><p class="skillDescription">While active, dealing Critical Damage heals you for 3300 Health. This effect can occur once every 1 second.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Increases the healing.</p>',
        icon: "/icons/skills/sorc/surge.png",
    },
    {
        name: "Streak",
        id: 23236,
        castTime: 0,
        target: "Self",
        range: 15,
        cost: {
            resourceName: "Magicka",
            amount: 3780,
        },
        description: '<p class="skillDescription">Transform yourself into pure energy and flash forward, dealing 2623 Shock Damage to enemies in your wake and stunning them for 3 seconds.</p><p class="skillDescription">This effect cannot be blocked.</p><p class="skillDescription">Casting again within 4 seconds costs 33% more Magicka.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Now deals damage and stuns enemies between your beginning and final location.</p>',
        icon: "/icons/skills/sorc/streak.png",
    },
]

export default sorcSkills
