import { GenericSkill } from "../../types/common"

const wardenSkills: Array<GenericSkill> = [
    {
        name: "Ice Fortress",
        id: 86130,
        costDetermined: false,
        castTime: 0,
        duration: 30,
        target: "Self",
        radius: 8,
        cost: {
            resourceName: "Magicka",
            amount: 4050,
        },
        description: '<p class="skillDescription">Wrap a thick cloak of ice around you and your grouped allies. The ice grants Major Resolve, increasing your Physical and Spell Resistance by 5948 for 30 seconds.</p><p class="skillDescription">You gain Minor Protection, reducing your damage taken by 5% for 30 seconds.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span></p>',
        icon: "/icons/skills/warden/ice_fortress.png",
    },
    {
        name: "Northern Storm",
        id: 86113,
        costDetermined: false,
        castTime: 0,
        duration: 8,
        radius: 10,
        target: "Area",
        cost: {
            resourceName: "Ultimate",
            amount: 200,
        },
        description: '<p class="skillDescription">Twist a violent storm around you, dealing 3279 Frost Damage every 1 second for 8 seconds to enemies around you and reducing their Movement Speed by 40%. As the storm holds, your Weapon and Spell Damage increases by 50 every 1 second for 5 seconds, up to 9 stacks max.</p><p class="skillDescription">You and nearby allies gain Major Protection, reducing your damage taken by 10%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Vastly increases damage done, and grants you ramping Weapon and Spell Damage for a brief time after activation.</p>',       
        icon: "/icons/skills/warden/northern.png",
    },
    {
        name: "Living Trellis",
        id: 85851,
        costDetermined: false,
        castTime: 0,
        target: "Area",
        targetAreaX: 28,
        targetAreaY: 12,
        radius: 28,
        duration: 10,
        cost: {
            resourceName: "Magicka",
            amount: 2700,
        },
        description: '<p class="skillDescription">Grow vines to embrace you or the lowest health ally in front of you for 10 seconds. The vines heal the target for 1310 Health each time they take damage. This effect can occur once every 1 second.</p><p class="skillDescription">When the vines expire, they heal the target for an additional 3176 Health.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Heals when effect ends.</p>',
        icon: "/icons/skills/warden/trellis.png",
    },
    {
        name: "Lotus Blossom",
        id: 85855,
        costDetermined: false,
        castTime: 0,
        target: "Area",
        radius: 28,
        duration: 60,
        cost: {
            resourceName: "Magicka",
            amount: 1350,
        },
        description: '<p class="skillDescription">Embrace the lotus blessing, causing your Light Attacks to restore 1320 Health and your fully-charged Heavy Attacks to restore 3960 Health to you or a nearby ally for 1 minute.</p><p class="skillDescription">While active you gain Major Prophecy and Savagery, increasing your Spell and Weapon Critical rating by 2629.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Significantly increases the duration.</p>',
        icon: "/icons/skills/warden/blossom.png",
    },
    {
        name: "Deep Fissure",
        id: 86015,
        costDetermined: false,
        castTime: 0,
        target: "Area",
        targetAreaX: 20,
        targetAreaY: 7,
        radius: 20,
        duration: 9,
        cost: {
            resourceName: "Magicka",
            amount: 2700,
        },
        description: '<p class="skillDescription">Stir a group of shalk that attack after 3 seconds, dealing 4723 Magic Damage to enemies in front of you.</p><p class="skillDescription">After the shalk complete their attack, they burrow underground for 6 seconds and then resurface again, dealing 6560 Magic Damage to enemies in front of you.</p><p class="skillDescription">Enemies damaged are afflicted with Major and Minor Breach, reducing their Physical and Spell Resistance by 5948 and 2974 for 10 seconds.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span></p>',
        icon: "/icons/skills/warden/deep.png",
    },
    {
        name: "Blue Betty",
        id: 86054,
        costDetermined: false,
        castTime: 0,
        target: "Self",
        duration: 25,
        description: '<p class="skillDescription">Call a betty netch to your side, which restores 4416 Magicka to you over 25 seconds and grants you Major Brutality and Sorcery, increasing your Weapon and Spell Damage by 20%.</p><p class="skillDescription">Every 5 seconds, the netch removes 1 negative effect from you. If no negative effects are removed you instead increase your damage done by 5% for 5 seconds.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Restores Magicka every second while active.</p>',
        icon: "/icons/skills/warden/bluebetty.png",
    },
    {
        name: "Bird of Prey",
        id: 86045,
        costDetermined: false,
        castTime: 0,
        target: "Self",
        duration: 6,
        cost: {
            resourceName: "Magicka",
            amount: 2700 ,
        },
        description: '<p class="skillDescription">Invoke the spirit of agility to gain Major Expedition for 6 seconds, increasing your Movement Speed by 30%.</p><p class="skillDescription">Gain immunity to snares and immobilizations for 4 seconds.</p><p class="skillDescription">While slotted you gain Minor Berserk, increasing your damage done by 5%.</p><p class="skillDescription newEffect"><span class="newEffectBanner">NEW EFFECT</span>Passively grants Minor Berserk while slotted.</p>',
        icon: "/icons/skills/warden/birdofprey.png",
    }
]

export default wardenSkills;